### ISSUE TITLE
Memory leak in InstabugInternalTrackingDelegate

### ISSUE THREAD

**Issue by mateusgrb** [Instabug/Instabug-Android#155]
The field `activityInstance` from `InstabugInternalTrackingDelegate` is leaking the instance of the last activity to be finished in my app.

### Steps to Reproduce the Problem
Run app that has instabug library added. Press back on home activity(last in the backstack).

### Expected Behavior
App closes without memory leaks.

### Actual Behavior
App closes with a memory leak:
![device-2018-12-19-160610](https://user-images.githubusercontent.com/1141910/50242728-f8cc3680-03a9-11e9-8b06-d6a9b55561e1.png)

### Instabug integration code
```
private void setupInstabug() {
        new Instabug.Builder(this, environmentUtil.isProduction() ?
                Res.getString(R.string.instabug_production_api_key) :
                Res.getString(R.string.instabug_develop_api_key))
                .setInvocationEvent(InstabugInvocationEvent.SHAKE)
                .setConsoleLogState(Feature.State.ENABLED)
                .setTrackingUserStepsState(Feature.State.ENABLED)
                .setInstabugLogState(Feature.State.ENABLED)
                .setInAppMessagingState(Feature.State.DISABLED)
                .build();
        Instabug.setShakingThreshold(Res.getInt(R.integer.instabug_shake_threshold));
        Instabug.setIntroMessageEnabled(false);
    }
```

### SDK Version
Was using `8.0.4` but also tried with `8.0.14` and the leak is still there.

### Android Version
8.1.0

### Device Model
Nexus 6P

**Comment by vezikon** [comment]
Hi @mateusgrb, `8.0.14.12-SNAPSHOT` has the fix for this. 

Please, don't forget to add this to your app-level build.gradle file in order to grab the snapshot. 

```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by mateusgrb** [comment]
@vezikon thanks. Is that a stable version or should I wait for `8.0.15`?

**Comment by vezikon** [comment]
@mateusgrb it is stable.

**Comment by mzelzoghbi** [comment]
Hi @mateusgrb, I’m closing this issue because of inactivity. Please reopen if you still encounter this issue with the latest version 8.0.19 Thank you! 😊

**Comment by BWMuller** [comment]
Hi @mzelzoghbi, just checked with 8.1.2 and the memory leak is still there. When looking at the delegate file its because there is a WeakReference currentActivity variable as well as a activityInstance that both hold the same activity. The activityInstance should be removed and the currentActivity reference should be used instead. The reference should be cleared once the activity is destroyed.

**Comment by mzelzoghbi** [comment]
Hi @BWMuller,  This fix is planned to be included in the next release, however, we created a new snapshot **8.1.2.9-SNAPSHOT** from the latest version. It's completely safe to use and has no debug code at all. I'll reopen this and keep it opened till this fix is officially released.

**Comment by BWMuller** [comment]
Hi @mzelzoghbi. Thank you for the update. I had a look at the snapshot. The weakreference just needs to be cleared when the activity is destroyed in the handleActivityDestroyedEvent method

**Comment by mzelzoghbi** [comment]
Hi @BWMuller, can you check this snapshot please **8.1.2.11-SNAPSHOT** ?

**Comment by BWMuller** [comment]
Hi @mzelzoghbi, seems to be releasing the activity fine now according to LeakCanary. Thank you for the effort

**Comment by mzelzoghbi** [comment]
@BWMuller Glad to hear that things are solved now :) If you face any problem, I will be happy to help you. Have a nice day 😄

**Comment by mateusgrb** [comment]
Hey @mzelzoghbi, I tried the following versions:
8.2.2.11-SNAPSHOT
8.2.2
8.2.0
8.0.19

All of them still have the memory leak.

The only one I found with the leak fixed is 8.1.2.11-SNAPSHOT.

**Comment by mzelzoghbi** [comment]
Hello @mateusgrb, this fix will be released the next week, for now, you can try this snapshot from latest version **8.2.2.16-SNAPSHOT**

**Comment by mzelzoghbi** [comment]
Hi @mateusgrb, I’m closing this issue because it has been fixed and released. Please reopen if you still encounter this issue with the latest version **8.3.0** Thank you! 😊

**Comment by GonnaGitYou** [comment]
We are seeing the same behavior when pressing back from the home activity in version 10.1.0.
HEAP ANALYSIS RESULT
    ====================================
    1 APPLICATION LEAKS
    
    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.
    
    1262303 bytes retained by leaking objects
    Signature: 65799f4111ddbb65c767c567b21246c3d2e93477
    ┬───
    │ GC Root: Input or output parameters in native code
    │
    ├─ okio.AsyncTimeout class
    │    Leaking: NO (PathClassLoader↓ is not leaking and a class is never leaking)
    │    ↓ static AsyncTimeout.$class$classLoader
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (InvocationManager↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ PathClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (InvocationManager↓ is not leaking)
    │    ↓ Object[].[1423]
    ├─ com.instabug.library.invocation.InvocationManager class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static InvocationManager.INSTANCE
    │                               ~~~~~~~~
    ├─ com.instabug.library.invocation.InvocationManager instance
    │    Leaking: UNKNOWN
    │    ↓ InvocationManager.currentInvokers
    │                        ~~~~~~~~~~~~~~~
    ├─ java.util.ArrayList instance
    │    Leaking: UNKNOWN
    │    ↓ ArrayList.elementData
    │                ~~~~~~~~~~~
    ├─ java.lang.Object[] array
    │    Leaking: UNKNOWN
    │    ↓ Object[].[1]
    │               ~~~
    ├─ com.instabug.library.invocation.d.b instance
    │    Leaking: UNKNOWN
    │    ↓ b.j
    │        ~
    ├─ com.instabug.library.invocation.d.b$f instance
    │    Leaking: YES (View.mContext references a destroyed activity)
    │    mContext instance of one.block.b1x.presentation.view.activities.MainActivity with mDestroyed = true
    │    View#mParent is null
    │    View#mAttachInfo is null (view detached)
    │    View.mWindowAttachCount = 1
    │    ↓ b$f.mContext
    ╰→ one.block.b1x.presentation.view.activities.MainActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because one.block.b1x.presentation.view.activities.MainActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     key = 393a1349-acbc-4058-a738-c5b534bb60e6
    ​     watchDurationMillis = 5303
    ​     retainedDurationMillis = 269
    ====================================
