### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#236]
We got a bunch of OutOfMemory error with regards to following method calls:

1.

```
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 864664 byte allocation with 631616 free bytes and 616KB until OOM, target footprint 201326592, growth limit 201326592
lgc: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 864664 byte allocation with 631616 free bytes and 616KB until OOM, target footprint 201326592, growth limit 201326592
	at lsm.a(SourceFile:367)
	at lqw.run(SourceFile:69)
	at lqw.call(SourceFile:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 864664 byte allocation with 631616 free bytes and 616KB until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:208)
	at java.nio.CharBuffer.toString(CharBuffer.java:1074)
	at java.util.regex.Matcher.reset(Matcher.java:1181)
	at java.util.regex.Matcher.reset(Matcher.java:280)
	at java.util.Scanner.readInput(Scanner.java:837)
	at java.util.Scanner.next(Scanner.java:1392)
	at com.instabug.library.network.NetworkManager.convertStreamToString(SourceFile:330)
	at com.instabug.library.network.NetworkManager.handleRequestResponse(SourceFile:295)
	at com.instabug.library.network.NetworkManager.access$500(SourceFile:38)
	at com.instabug.library.network.NetworkManager$1.subscribe(SourceFile:126)
	at lli.subscribeActual(SourceFile:40)
	at lez.subscribe(SourceFile:12246)
	at loq$b.run(SourceFile:96)
	at lfh$a.run(SourceFile:578)
	at lqw.run(SourceFile:66)
	... 6 more
java.lang.OutOfMemoryError: Failed to allocate a 864664 byte allocation with 631616 free bytes and 616KB until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:208)
	at java.nio.CharBuffer.toString(CharBuffer.java:1074)
	at java.util.regex.Matcher.reset(Matcher.java:1181)
	at java.util.regex.Matcher.reset(Matcher.java:280)
	at java.util.Scanner.readInput(Scanner.java:837)
	at java.util.Scanner.next(Scanner.java:1392)
	at com.instabug.library.network.NetworkManager.convertStreamToString(SourceFile:330)
	at com.instabug.library.network.NetworkManager.handleRequestResponse(SourceFile:295)
	at com.instabug.library.network.NetworkManager.access$500(SourceFile:38)
	at com.instabug.library.network.NetworkManager$1.subscribe(SourceFile:126)
	at lli.subscribeActual(SourceFile:40)
	at lez.subscribe(SourceFile:12246)
	at loq$b.run(SourceFile:96)
	at lfh$a.run(SourceFile:578)
	at lqw.run(SourceFile:66)
	at lqw.call(SourceFile:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

2.
```
Failed to allocate a 513588 byte allocation with 285838 free bytes and 279KB until OOM
java.lang.OutOfMemoryError: Failed to allocate a 513588 byte allocation with 285838 free bytes and 279KB until OOM
	at com.instabug.library.internal.storage.Encryptor.a(SourceFile:55)
	at com.instabug.library.internal.storage.Encryptor.a(SourceFile:32)
	at com.instabug.library.core.InstabugCore.encrypt(SourceFile:167)
	at jdd$4$1.safedk_InstabugCore_encrypt_9bfa175eb56f9f92fba6d7dcd366f04b(SourceFile)
	at jdd$4$1.onSuccess(SourceFile:352)
	at com.instabug.library.util.BitmapUtils$2.run(SourceFile:257)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at jct$1.run(SourceFile:28)
	at java.lang.Thread.run(Thread.java:818)
```

3.
```
Failed to allocate a 454844 byte allocation with 0 free bytes and 3GB until OOM
java.lang.OutOfMemoryError: Failed to allocate a 454844 byte allocation with 0 free bytes and 3GB until OOM
	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:840)
	at javax.crypto.Cipher.doFinal(Cipher.java:1502)
	at com.instabug.library.internal.storage.Encryptor.a(SourceFile:60)
	at com.instabug.library.internal.storage.Encryptor.a(SourceFile:32)
	at com.instabug.library.core.InstabugCore.encrypt(SourceFile:167)
	at jdd$4$1.safedk_InstabugCore_encrypt_9bfa175eb56f9f92fba6d7dcd366f04b(SourceFile)
	at jdd$4$1.onSuccess(SourceFile:352)
	at com.instabug.library.util.BitmapUtils$2.run(SourceFile:257)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at jct$1.run(SourceFile:28)
	at java.lang.Thread.run(Thread.java:818)
```

### Steps to Reproduce the Problem
N/A

### Instabug integration code
```
new Instabug.Builder(application, application.getString(R.string.instabug_app_id))
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();
        Replies.setPushNotificationState(Feature.State.ENABLED);
        Instabug.setDebugEnabled(!AppBuildConfig.App.IS_RELEASE);
        Instabug.setPrimaryColor(ResourcesCompat.getColor(getResources(), R.color.under9_theme_black, null));
        // Arguments:initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
        BugReporting.setAttachmentTypesEnabled(false, true, true, true);
        Surveys.setShouldShowWelcomeScreen(true);
        Chats.setState(Feature.State.DISABLED);
        CrashReporting.setState(Feature.State.DISABLED);
```

### SDK Version
8.7.0

### Android Version
Android 5 - 7 (Not found on 8 or above)

**Comment by odemolliens** [comment]
Same here

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 1184912 byte allocation with 1019936 free bytes and 996KB until OOM, max allowed footprint 134217728, growth limit 134217728
       at java.lang.StringFactory.newStringFromChars + 220(StringFactory.java:220)
       at java.nio.HeapCharBuffer.toString + 208(HeapCharBuffer.java:208)
       at java.nio.CharBuffer.toString + 902(CharBuffer.java:902)
       at java.util.regex.Matcher.reset + 1073(Matcher.java:1073)
       at java.util.regex.Matcher.reset + 1045(Matcher.java:1045)
       at java.util.Scanner.readInput + 832(Scanner.java:832)
       at java.util.Scanner.next + 1386(Scanner.java:1386)
       at com.instabug.library.network.NetworkManager.convertStreamToString + 330(NetworkManager.java:330)
       at com.instabug.library.network.NetworkManager.handleRequestResponse + 295(NetworkManager.java:295)
       at com.instabug.library.network.NetworkManager.access$500 + 38(NetworkManager.java:38)
       at com.instabug.library.network.NetworkManager$1.subscribe + 126(NetworkManager.java:126)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual + 40(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe + 12025(Observable.java:12025)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run + 96(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run + 571(Scheduler.java:571)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 66(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call + 57(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run + 266(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 301(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 764(Thread.java:764)
```

**Comment by mzelzoghbi** [comment]
Hello @raymondctc   @odemolliens 
First of all, please accept our sincerest apologies for taking some time to respond. 
This was fixed in our latest version 9.0.3 Please give it a try, and let me know if it solves the issues you have. Thank you 😊

**Comment by SKerencic** [comment]
Hi.

I still have this issue on version 9.0.3 for android 5 - 7 (Not found on 8 or above).
Was is maybe fixed on 9.0.5?

tnx
