### ISSUE TITLE
Instabug is not responding to `show()` call or Shake event

### ISSUE THREAD

**Issue by fluxxion82** [Instabug/Instabug-Android#247]
### Steps to Reproduce the Problem
Add 
`new Instabug.Builder(this, "APP_TOKEN").build();`
in Application's onCreate method.

Next, use 'Shake' invocation or call
`Instabug.show()` (This is being launched from a kotlin coroutine `launch` with default context. Calling launch from the main context doesn't seem to help either though.)

### Expected Behavior
Instabug bug reporting dialog shows up

### Actual Behavior
Nothing happens very often. Started getting reports that Instabug wasn't working on version 8.4.0, although it seems to be working fine on some phones. Tried to update the Instabug lib version to see if that helps but same results. Some phone models haven't experienced the issue at all, other models it happens occasionally, and others it happens all the time, with both sdk versions listed. We seem to be getting crash reports from the phones fine, however.

### Instabug integration code
Instabug.Builder(application, <token>)
                        .setInvocationEvents(InstabugInvocationEvent.SHAKE) // also using NONE
                        .setConsoleLogState(Feature.State.ENABLED)
                        .setUserDataState(Feature.State.ENABLED)
                        .setTrackingUserStepsState(Feature.State.ENABLED)
                        .setInAppMessagingState(Feature.State.ENABLED)
                        .setInstabugLogState(Feature.State.ENABLED)
                        .build()
CrashReporting.setState(Feature.State.ENABLED)
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)

### SDK Version
8.4.0 and 8.7.2

### Android Version
Android 8 and up

### Device Model
Consistent issue on Nexus 6P (android v8.1.0)
Happens occasionally on LG Thinq (android v9), Pixel 2 (android v9), Pixel 3a (android v10) and Nexus 2.2 (android v9)
Working fine on Pixel 3 (android v10)

**Comment by sweaver2494** [comment]
I am having the same issue on a Pixel 3A. It was working a few weeks ago, but I just realized that it stopped working sometime in the last few weeks. During this time, my phone upgraded to version 10 (on Oct 1 2019).

I call Instabug.show() upon a toolbar menu button click, but now nothing happens. I also tried BugReporting.show(BugReporting.ReportType.Bug) instead of Instabug.show(), but with the same results.

At the beginning of my MainActivity, I have:
```
String instabug_app_token = "my app token";
new Instabug.Builder(getApplication(), instabug_app_token)
        .setInvocationEvents(InstabugInvocationEvent.NONE)
        .build();
```
Then upon a toolbar menu button press, I have:
`Instabug.show();`
In my AndroidManifest.xml, right before the <application> block, I have:
```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" tools:node="remove" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
```
In my gradle dependencies, I have:
`implementation 'com.instabug.library:instabug:8.7.2'`

Thanks for your help!

**Comment by mzelzoghbi** [comment]
@sweaver2494 Thanks for reaching out.
I can see that you are initializing the SDK in the Main Activity and this causes some issues.

We would recommend initializing the SDK in the Application class and let us know if it is still not working.

For now, I'll be closing this. Please feel free to re-open if you still encounter any issues

**Comment by fluxxion82** [comment]
I actually just finished creating a test app that reproduces part of the issues we are seeing. I found a race condition with the building of Instabug and updating the user info, but there is an issue when we first run the app, Instabug won't show. If we exit the app and then reopen the app, instabug seems to work normally. If we force close the app, and reopen the app, instabug won't show. We are initializing Instabug in the Application. I will post the sample code in a couple of hours.

**Comment by fluxxion82** [comment]
Ok, here is an example app. Sorry it took so long. Instabug is built in the onCreate method of the application. Like I mention in the above comment, the first time you run the app, hit the settings button on the bottom nav bar, and then you click the 'send diagnostic report' button, and that calls Instabug.show(), but nothing happens. If you background the app, and then bring it to the foreground and click on the 'send diagnostic report' button again, Instabug then shows up. If you force close the app and reopen it and follow the steps again, Instabug does not show. Let me know if you have any questions about how things work..hopefully it isn't too complicated. The repo is at git@github.com:fluxxion82/Instabug-Test-App.git

**Comment by mzelzoghbi** [comment]
@fluxxion82 Thank You for your time, we really appreciate your effort to reproduce the issue and help us to figure out what is the issue. We figured out that there is a delay around 1 second between initializing the SDK directly from the application class &  from using `DI` & `Courtine `. 

The root cause that the SDK will not be initialized when it is delayed in init() because we listen on activity create/destroy events from activity component callbacks to enable some SDK functionalities. This event gets fired right after the activity created and in case there is a delay in SDK init() the event gets posted before we start listening. So we will be looking into this to find a fix. But for now, you can just add the Instabug SDK Builder Block in the **oncreate** method of your application class without using any 3rd parties or DIs and we will get back to you once we have a solid fix.

Thank You!

**Comment by sweaver2494** [comment]
I moved the Instabug.build() block into the oncreate method of the application class, but unfortunately that did not fix it :( Still nothing happends when I call Instabug.show().
I wonder if my issue is different, as it does not even show up after backgrounding the app, as in @fluxxion82 's case.

**Comment by mzelzoghbi** [comment]
@sweaver2494  is this issue reproducible on a sample app?

**Comment by fluxxion82** [comment]
@mzelzoghbi fyi, It looks like the latest updates fix the delay issue for me.

**Comment by mzelzoghbi** [comment]
@fluxxion82 This is Interesting 🤔 Technically we didn't change any logic related to this area, all the recent changes were various bug fixes and the major change was migrating to AndroidX. But anyway, I am happy that your issue has been fixed 🎉 

@sweaver2494 can you migrate to the latest SDK Version 9.0.3 and check if this issue still happening?

**Comment by sweaver2494** [comment]
@mzelzoghbi I migrated to 9.0.3, but still no luck. I am using AndroidX by the way.

I have no indication that anything is happening when I call Instabug.show(), other than a log message:
SDK LOG: encryption: ivparameter<parameter> key: <key>

**Comment by mzelzoghbi** [comment]
@sweaver2494 We will need more info about your account so, Would you be able to reach out to our support team using contactus@instabug.com so that we can further investigate this issue? 

ThankYou

**Comment by fluxxion82** [comment]
So I think I'm seeing this issue on an LG Thinq still. It's weird because the logging we've added looks like the build call is happening before any of the api calls, but I'm still getting an exception about api being called before build. After that library update I haven't seen or heard of any issues with instabug, but I just saw it while testing on this phone, which is not the type of phone most of our users are using. Anyways, perhaps the issue isn't completely fixed as it seemed previously.
