### ISSUE TITLE
Crash when using Instabug

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#294]
### Expected Behavior
app don't crash
### Actual Behavior
Crash with stack trace:
Current date: 2020-04-20 17:31:19 Device: Samsung SM-T387VK  Stack trace:  io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)	at java.lang.Thread.run(Thread.java:764)Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.instabug.library.network.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_network_authorization_NetworkOfficer_getClientId__)	at com.instabug.library.network.authorization.NetworkOfficer.getClientId(Native Method)	at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)	at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)	at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)	at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)	at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)	at io.reactivex.Observable.subscribe(Observable.java:12025)	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)	... 6 more

### Instabug integration code
 Instabug.Builder(this@SkynetApp, WebServiceApi.INSTABUG_KEY)
                        .setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
                        .setReproStepsState(State.ENABLED)
                        .setConsoleLogState(Feature.State.ENABLED)
                        .build()
                FeatureRequests.setEmailFieldRequired(false, ActionType.ADD_COMMENT_TO_FEATURE)
                BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)
                Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
                BugReporting.setReportTypes(BugReporting.ReportType.BUG)
                Instabug.setSessionProfilerState(Feature.State.ENABLED)

### SDK Version
9.1.0

### Android Version
8.1.0

### Device Model
 Samsung SM-T387VK

**Comment by Muhammadyoussef** [comment]
Hi @dung90it,

Would you pleaser try invalidating Android studio cache and performing a clean build/install to your project and let us know whether or not this crash is still happening 🙏

**Comment by mzelzoghbi** [comment]
Hi @dung90it, Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.4.8-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by azubchenko** [comment]
Experiencing the same problem on pure 9.1.4 version of SDK, 9.1.4.8 fixes the problem

**Comment by mzelzoghbi** [comment]
@azubchenko This has been fixed in **9.1.5**. Please feel free to reopen if you encountered the same issue again.

Thank You 😊

**Comment by jimmy0251** [comment]
I had this issue on old builds which were using 9.1.4 sdk version. However, newer builds do not have this issue, did you guys patch 9.1.4 version too?

**Comment by huanvu** [comment]
I've experienced this on 9.1.6

**Comment by MahmoudAmin39** [comment]
Hi @huanvu , Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.4.8-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by dpnolte** [comment]
Is this fixed in 9.1.5 and above? I've also a crash report as described above with version 9.1.6. I'm trying out the snapshot version now

**Comment by marcoRS** [comment]
Hello, this is still happening as of Instabug version `10.10.1`. We are seeing the exception as: 
`
Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for java.lang.String com.instabug.library.networkv2.authorization.NetworkOfficer.getClientId() (tried Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId and Java_com_instabug_library_networkv2_authorization_NetworkOfficer_getClientId__)
`

This is a crash on our production app. Should this issue be reopened? @Muhammadyoussef
