### ISSUE TITLE
Robolectric test issue: UnsatisfiedLinkError - Instabug NetworkOfficer.getClientId()

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#305]
### Steps to Reproduce the Problem

Run a robolectric test -- The class I'm testing is not doing any instabug stuff, so I don't really know where it's coming from.

### Expected Behavior

No exceptions show up

### Actual Behavior

This error shows up when running a Robolectric test:
```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at com.instabug.library.network.authorization.NetworkOfficer.getClientId(Native Method)
	at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)
	at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)
	at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)
	at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
	at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 7 more
```

### Instabug integration code
In App.kt (Application class)
```kt
        Instabug.Builder(this, ResourcesHelper.getString(R.string.INSTABUG_SECRET))
                .setInvocationEvents(
                    InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT
                )
                .build()
        Instabug.setLocale(Locale.getDefault())
```

### SDK Version
Instabug 9.1.4, Robolectric 4.3.1

### Android Version
Target SDK 29

### Device Model
Not relevant

**Comment by mzelzoghbi** [comment]
Hello @carstenhag  Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.4.8-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by carstenhag** [comment]
Hmm, I added the new version but it still shows the exceptions/errors.

`  brandXYZImplementation 'com.instabug.library:instabug:9.1.4.8-SNAPSHOT'`

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at com.instabug.library.network.authorization.NetworkOfficer.getClientId(Native Method)
	at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)
	at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)
	at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)
	at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
	at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 7 more
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.instabug.library.network.authorization.NetworkOfficer.getClientId()Ljava/lang/String;
	at com.instabug.library.network.authorization.NetworkOfficer.getClientId(Native Method)
	at com.instabug.library.network.authorization.NetworkOfficer.a(NetworkOfficer.java:9)
	at com.instabug.library.network.NetworkManager.buildConnection(NetworkManager.java:10)
	at com.instabug.library.network.NetworkManager.connectWithNormalType(NetworkManager.java:2)
	at com.instabug.library.network.NetworkManager.access$100(NetworkManager.java:1)
	at com.instabug.library.network.NetworkManager$a.subscribe(NetworkManager.java:20)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 7 more
```

**Comment by mzelzoghbi** [comment]
@carstenhag I am not sure what you are calling in the test case but probably the SDK is initialized tries to make a network request and that is causing the exception. Can you share with me a sample project with the issue so I can debug further?

**Comment by SudoPlz** [comment]
@mzelzoghbi we're getting that error in production, any idea if it's fixed on later versions of Instabug?

Thanks

**Comment by mzelzoghbi** [comment]
Hi @carstenhag @SudoPlz, 
This has been solved in our latest build `9.1.7`, please try it out and feel free to reach out if you faced any further issues. 

Thank You 😊

**Comment by SudoPlz** [comment]
@mzelzoghbi awesome, since we're using instabug-reactnative (our project is a react-native project) is there a corresponding release that includes your latest android sdk?

**Comment by AliAbdelfattah** [comment]
@SudoPlz expect our ReactNative release within the next week, you can follow up on the issue you've opened there since this issue is now closed 🙏

**Comment by carstenhag** [comment]
@mzelzoghbi  Sorry for not answering before, but yes, 9.1.7 and 9.1.8 don't show these issues anymore, thanks :). I have now noticed that 10.0.0 has a similar issue, see #340 for that.

**Comment by SudoPlz** [comment]
@carstenhag Is 10.0.0 the available for react-native yet? I only see 9.1.9 available for rn

**Comment by carstenhag** [comment]
@SudoPlz Sorry, I'm using the android lib, not the react native one.
