### ISSUE TITLE
10.5.0 Crash - Couldn't read row 0, col -1 from CursorWindow

### ISSUE THREAD

**Issue by laithnurie** [Instabug/Instabug-Android#380]
### Steps to Reproduce the Problem
Unable to reproduce locally unfortunately but it's happening to our live customers now where we had to halt our release.

This is started to happen after we upgrade from 10.4.3 to 10.5.0

### Expected Behavior
no crashing

### Actual Behavior
it crashes

### Instabug integration code
```
    fun init(application: Application) {
        Instabug.Builder(application, application.getString(R.string.instabug_application_token))
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .build()
        CrashReporting.setState(Feature.State.DISABLED)
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK, BugReporting.ReportType.QUESTION)
        BugReporting.setAttachmentTypesEnabled(false, true, true, true)
        BugReporting.setOptions(Option.EMAIL_FIELD_HIDDEN, Option.COMMENT_FIELD_REQUIRED)
        BugReporting.setReportTypes(BugReporting.ReportType.BUG)
        Instabug.setPrimaryColor(ContextCompat.getColor(application, R.color.teal_100))
        val placeholder = InstabugCustomTextPlaceHolder().apply {
            set(InstabugCustomTextPlaceHolder.Key.SUCCESS_DIALOG_HEADER, application.getString(R.string.feedback_thank_you_dialog_title))
            set(InstabugCustomTextPlaceHolder.Key.REPORT_SUCCESSFULLY_SENT, application.getString(R.string.feedback_thank_you_dialog_message))
            set(InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_BUG_REPORT, application.getString(R.string.feedback_rationale_hint))
            set(InstabugCustomTextPlaceHolder.Key.COMMENT_FIELD_HINT_FOR_FEEDBACK, application.getString(R.string.feedback_rationale_hint))
        }
        Instabug.setCustomTextPlaceHolders(placeholder)

        BugReporting.setOnDismissCallback { dismissType, _ ->
            if (dismissType == OnSdkDismissCallback.DismissType.SUBMIT) {
                // save in preferences
            }
        }
    }
```

### SDK Version
10.5.0

### Android Version
8-10

### Device Model
Multiple device:
Galaxy S9+
Redmi Note 7
Redmi 5 Plus
A53

### Stacktrace
```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:469)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
       at com.instabug.library.m.c$i.subscribe(c.java:29)
       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.maybe.MaybeFilterSingle.subscribeActual(MaybeFilterSingle.java:40)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
       at io.reactivex.Maybe.subscribe(Maybe.java:4290)
       at io.reactivex.internal.operators.maybe.MaybeFlatMapCompletable.subscribeActual(MaybeFlatMapCompletable.java:44)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
       at io.reactivex.internal.disposables.EmptyDisposable.complete(EmptyDisposable.java:68)
       at io.reactivex.internal.operators.completable.CompletableEmpty.subscribeActual(CompletableEmpty.java:27)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by MShannan** [comment]
@laithnurie Thanks for reporting this, 
Can you tell us where/when do you call the function  `init(application: Application)` where you initialize our SDK? and if you call it from the background/main thread?

**Comment by laithnurie** [comment]
> @laithnurie Thanks for reporting this,
> Can you tell us where/when do you call the function `init(application: Application)` where you initialize our SDK? and if you call it from the background/main thread?

Hi @MShannan, we call it from the Application class direction, we are passing the application itself as a parameter

**Comment by MShannan** [comment]
Hi @laithnurie So you mean that the method is called from the Application class in `oncreate()` method, right?

**Comment by laithnurie** [comment]
> Hi @laithnurie So you mean that the method is called from the Application class in `oncreate()` method, right?

That's correct :)

**Comment by MShannan** [comment]
thanks alot for verifying, we are looking into it right now and will get back to you ASAP

**Comment by laithnurie** [comment]
> thanks alot for verifying, we are looking into it right now and will get back to you ASAP

Thank you

**Comment by laithnurie** [comment]
hey @MShannan, any updates about this ? For now, we hotfixed the release and downgrade it to 10.4.3 and the problem is not happening anymore.

**Comment by MShannan** [comment]
Hello @laithnurie 
We created a SNAPSHOT that should fix the issue.
` implmentation 'com.instabug.library:instabug:10.5.0.3229-SNAPSHOT'`
you will need to add these lines to your app build.gradle before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This fix will be included in our next official release that should come out in the next few days.
I will close this issue for now, please feel free to reopen it again if you have any further issues.
Thank You 😃

**Comment by laithnurie** [comment]
@MShannan thank you for the quick response.

We will make another release week so we will just wait for the official release.

Thank you again, I will close the issue and I will keep an eye on your repo once a new official release is out.

**Comment by Gerlac** [comment]
@MShannan We updated to version `10.5.1` and we can still see the issue in prod. Was the fix for this issue included in `10.5.1`?

**Comment by MShannan** [comment]
Hi @Gerlac. The fix wasn't included in 10.5.1, Please update to the latest version 10.7.0 which have this issue fixed.

**Comment by Gerlac** [comment]
OK, great! Thanks @MShannan
